export const ListaComunasBarriosMedellin = [
  {
    COMUNA: 1,
    BARRIO: 8,
    NOMBRE_BARRIO: 'El Compromiso',
    NOMBRE_COMUNA: 'POPULAR',
  },
  {
    COMUNA: 1,
    BARRIO: 12,
    NOMBRE_BARRIO: 'Carpinelo',
    NOMBRE_COMUNA: 'POPULAR',
  },
  {
    COMUNA: 1,
    BARRIO: 4,
    NOMBRE_BARRIO: 'Granizal',
    NOMBRE_COMUNA: 'POPULAR',
  },
  {
    COMUNA: 1,
    BARRIO: 1,
    NOMBRE_BARRIO: 'Santo Domingo Savio No. 1',
    NOMBRE_COMUNA: 'POPULAR',
  },
  {
    COMUNA: 1,
    BARRIO: 10,
    NOMBRE_BARRIO: 'La Esperanza No. 2',
    NOMBRE_COMUNA: 'POPULAR',
  },
  {
    COMUNA: 1,
    BARRIO: 9,
    NOMBRE_BARRIO: 'Aldea Pablo VI',
    NOMBRE_COMUNA: 'POPULAR',
  },
  {
    COMUNA: 1,
    BARRIO: 7,
    NOMBRE_BARRIO: 'San Pablo',
    NOMBRE_COMUNA: 'POPULAR',
  },
  {
    COMUNA: 1,
    BARRIO: 5,
    NOMBRE_BARRIO: 'Moscú No. 2',
    NOMBRE_COMUNA: 'POPULAR',
  },
  {
    COMUNA: 1,
    BARRIO: 6,
    NOMBRE_BARRIO: 'Villa Guadalupe',
    NOMBRE_COMUNA: 'POPULAR',
  },
  {
    COMUNA: 1,
    BARRIO: 11,
    NOMBRE_BARRIO: 'La Avanzada',
    NOMBRE_COMUNA: 'POPULAR',
  },
  {
    COMUNA: 1,
    BARRIO: 2,
    NOMBRE_BARRIO: 'Santo Domingo Savio No. 2',
    NOMBRE_COMUNA: 'POPULAR',
  },
  {
    COMUNA: 1,
    BARRIO: 3,
    NOMBRE_BARRIO: 'Popular',
    NOMBRE_COMUNA: 'POPULAR',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 2,
    BARRIO: 3,
    NOMBRE_BARRIO: 'Pablo VI',
    NOMBRE_COMUNA: 'SANTA CRUZ',
  },
  {
    COMUNA: 2,
    BARRIO: 1,
    NOMBRE_BARRIO: 'La Isla',
    NOMBRE_COMUNA: 'SANTA CRUZ',
  },
  {
    COMUNA: 2,
    BARRIO: 5,
    NOMBRE_BARRIO: 'La Francia',
    NOMBRE_COMUNA: 'SANTA CRUZ',
  },
  {
    COMUNA: 2,
    BARRIO: 9,
    NOMBRE_BARRIO: 'Moscú No. 1',
    NOMBRE_COMUNA: 'SANTA CRUZ',
  },
  {
    COMUNA: 2,
    BARRIO: 4,
    NOMBRE_BARRIO: 'La Frontera',
    NOMBRE_COMUNA: 'SANTA CRUZ',
  },
  {
    COMUNA: 2,
    BARRIO: 7,
    NOMBRE_BARRIO: 'Villa del Socorro',
    NOMBRE_COMUNA: 'SANTA CRUZ',
  },
  {
    COMUNA: 2,
    BARRIO: 10,
    NOMBRE_BARRIO: 'Santa Cruz',
    NOMBRE_COMUNA: 'SANTA CRUZ',
  },
  {
    COMUNA: 2,
    BARRIO: 6,
    NOMBRE_BARRIO: 'Andalucía',
    NOMBRE_COMUNA: 'SANTA CRUZ',
  },
  {
    COMUNA: 2,
    BARRIO: 8,
    NOMBRE_BARRIO: 'Villa Niza',
    NOMBRE_COMUNA: 'SANTA CRUZ',
  },
  {
    COMUNA: 2,
    BARRIO: 2,
    NOMBRE_BARRIO: 'Playón de Los Comuneros',
    NOMBRE_COMUNA: 'SANTA CRUZ',
  },
  {
    COMUNA: 2,
    BARRIO: 11,
    NOMBRE_BARRIO: 'La Rosa',
    NOMBRE_COMUNA: 'SANTA CRUZ',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 3,
    BARRIO: 8,
    NOMBRE_BARRIO: 'Manrique Oriental',
    NOMBRE_COMUNA: 'MANRIQUE',
  },
  {
    COMUNA: 3,
    BARRIO: 15,
    NOMBRE_BARRIO: 'San José la Cima No.2',
    NOMBRE_COMUNA: 'MANRIQUE',
  },
  {
    COMUNA: 3,
    BARRIO: 10,
    NOMBRE_BARRIO: 'Versalles No. 2',
    NOMBRE_COMUNA: 'MANRIQUE',
  },
  {
    COMUNA: 3,
    BARRIO: 14,
    NOMBRE_BARRIO: 'San José la Cima No. 1',
    NOMBRE_COMUNA: 'MANRIQUE',
  },
  {
    COMUNA: 3,
    BARRIO: 6,
    NOMBRE_BARRIO: 'El Pomar',
    NOMBRE_COMUNA: 'MANRIQUE',
  },
  {
    COMUNA: 3,
    BARRIO: 4,
    NOMBRE_BARRIO: 'Santa Inés',
    NOMBRE_COMUNA: 'MANRIQUE',
  },
  {
    COMUNA: 3,
    BARRIO: 5,
    NOMBRE_BARRIO: 'El Raizal',
    NOMBRE_COMUNA: 'MANRIQUE',
  },
  {
    COMUNA: 3,
    BARRIO: 13,
    NOMBRE_BARRIO: 'María Cano Carambolas',
    NOMBRE_COMUNA: 'MANRIQUE',
  },
  {
    COMUNA: 3,
    BARRIO: 12,
    NOMBRE_BARRIO: 'Oriente',
    NOMBRE_COMUNA: 'MANRIQUE',
  },
  {
    COMUNA: 3,
    BARRIO: 9,
    NOMBRE_BARRIO: 'Versalles No. 1',
    NOMBRE_COMUNA: 'MANRIQUE',
  },
  {
    COMUNA: 3,
    BARRIO: 11,
    NOMBRE_BARRIO: 'La Cruz',
    NOMBRE_COMUNA: 'MANRIQUE',
  },
  {
    COMUNA: 3,
    BARRIO: 3,
    NOMBRE_BARRIO: 'Campo Valdés No. 2',
    NOMBRE_COMUNA: 'MANRIQUE',
  },
  {
    COMUNA: 3,
    BARRIO: 2,
    NOMBRE_BARRIO: 'Las Granjas',
    NOMBRE_COMUNA: 'MANRIQUE',
  },
  {
    COMUNA: 3,
    BARRIO: 7,
    NOMBRE_BARRIO: 'Manrique Central No. 2',
    NOMBRE_COMUNA: 'MANRIQUE',
  },
  {
    COMUNA: 3,
    BARRIO: 1,
    NOMBRE_BARRIO: 'La Salle',
    NOMBRE_COMUNA: 'MANRIQUE',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 4,
    BARRIO: 8,
    NOMBRE_BARRIO: 'San Pedro',
    NOMBRE_COMUNA: 'ARANJUEZ',
  },
  {
    COMUNA: 4,
    BARRIO: 4,
    NOMBRE_BARRIO: 'Bermejal-Los Alamos',
    NOMBRE_COMUNA: 'ARANJUEZ',
  },
  {
    COMUNA: 4,
    BARRIO: 1,
    NOMBRE_BARRIO: 'Berlin',
    NOMBRE_COMUNA: 'ARANJUEZ',
  },
  {
    COMUNA: 4,
    BARRIO: 2,
    NOMBRE_BARRIO: 'San Isidro',
    NOMBRE_COMUNA: 'ARANJUEZ',
  },
  {
    COMUNA: 4,
    BARRIO: 16,
    NOMBRE_BARRIO: 'Jardín Botánico',
    NOMBRE_COMUNA: 'ARANJUEZ',
  },
  {
    COMUNA: 4,
    BARRIO: 5,
    NOMBRE_BARRIO: 'Moravia',
    NOMBRE_COMUNA: 'ARANJUEZ',
  },
  {
    COMUNA: 4,
    BARRIO: 12,
    NOMBRE_BARRIO: 'La Piñuela',
    NOMBRE_COMUNA: 'ARANJUEZ',
  },
  {
    COMUNA: 4,
    BARRIO: 10,
    NOMBRE_BARRIO: 'Campo Valdés No. 1',
    NOMBRE_COMUNA: 'ARANJUEZ',
  },
  {
    COMUNA: 4,
    BARRIO: 7,
    NOMBRE_BARRIO: 'Sevilla',
    NOMBRE_COMUNA: 'ARANJUEZ',
  },
  {
    COMUNA: 4,
    BARRIO: 6,
    NOMBRE_BARRIO: 'Universidad de Antioquia',
    NOMBRE_COMUNA: 'ARANJUEZ',
  },
  {
    COMUNA: 4,
    BARRIO: 15,
    NOMBRE_BARRIO: 'Miranda',
    NOMBRE_COMUNA: 'ARANJUEZ',
  },
  {
    COMUNA: 4,
    BARRIO: 9,
    NOMBRE_BARRIO: 'Manrique Central No. 1',
    NOMBRE_COMUNA: 'ARANJUEZ',
  },
  {
    COMUNA: 4,
    BARRIO: 17,
    NOMBRE_BARRIO: 'Parque Norte',
    NOMBRE_COMUNA: 'ARANJUEZ',
  },
  {
    COMUNA: 4,
    BARRIO: 13,
    NOMBRE_BARRIO: 'Aranjuez',
    NOMBRE_COMUNA: 'ARANJUEZ',
  },
  {
    COMUNA: 4,
    BARRIO: 11,
    NOMBRE_BARRIO: 'Las Esmeraldas',
    NOMBRE_COMUNA: 'ARANJUEZ',
  },
  {
    COMUNA: 4,
    BARRIO: 3,
    NOMBRE_BARRIO: 'Palermo',
    NOMBRE_COMUNA: 'ARANJUEZ',
  },
  {
    COMUNA: 4,
    BARRIO: 14,
    NOMBRE_BARRIO: 'Brasilia',
    NOMBRE_COMUNA: 'ARANJUEZ',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 5,
    BARRIO: 4,
    NOMBRE_BARRIO: 'Tejelo',
    NOMBRE_COMUNA: 'CASTILLA',
  },
  {
    COMUNA: 5,
    BARRIO: 1,
    NOMBRE_BARRIO: 'Toscana',
    NOMBRE_COMUNA: 'CASTILLA',
  },
  {
    COMUNA: 5,
    BARRIO: 9,
    NOMBRE_BARRIO: 'Girardot',
    NOMBRE_COMUNA: 'CASTILLA',
  },
  {
    COMUNA: 5,
    BARRIO: 3,
    NOMBRE_BARRIO: 'Florencia',
    NOMBRE_COMUNA: 'CASTILLA',
  },
  {
    COMUNA: 5,
    BARRIO: 6,
    NOMBRE_BARRIO: 'Plaza de Ferias',
    NOMBRE_COMUNA: 'CASTILLA',
  },
  {
    COMUNA: 5,
    BARRIO: 15,
    NOMBRE_BARRIO: 'Cementerio Universal',
    NOMBRE_COMUNA: 'CASTILLA',
  },
  {
    COMUNA: 5,
    BARRIO: 2,
    NOMBRE_BARRIO: 'Las Brisas',
    NOMBRE_COMUNA: 'CASTILLA',
  },
  {
    COMUNA: 5,
    BARRIO: 11,
    NOMBRE_BARRIO: 'Castilla',
    NOMBRE_COMUNA: 'CASTILLA',
  },
  {
    COMUNA: 5,
    BARRIO: 17,
    NOMBRE_BARRIO: 'Caribe',
    NOMBRE_COMUNA: 'CASTILLA',
  },
  {
    COMUNA: 5,
    BARRIO: 16,
    NOMBRE_BARRIO: 'Terminal de Transporte',
    NOMBRE_COMUNA: 'CASTILLA',
  },
  {
    COMUNA: 5,
    BARRIO: 7,
    NOMBRE_BARRIO: 'Héctor Abad Gómez',
    NOMBRE_COMUNA: 'CASTILLA',
  },
  {
    COMUNA: 5,
    BARRIO: 5,
    NOMBRE_BARRIO: 'Boyacá',
    NOMBRE_COMUNA: 'CASTILLA',
  },
  {
    COMUNA: 5,
    BARRIO: 12,
    NOMBRE_BARRIO: 'Oleoducto',
    NOMBRE_COMUNA: 'CASTILLA',
  },
  {
    COMUNA: 5,
    BARRIO: 10,
    NOMBRE_BARRIO: 'Tricentenario',
    NOMBRE_COMUNA: 'CASTILLA',
  },
  {
    COMUNA: 5,
    BARRIO: 8,
    NOMBRE_BARRIO: 'Belalcázar',
    NOMBRE_COMUNA: 'CASTILLA',
  },
  {
    COMUNA: 5,
    BARRIO: 13,
    NOMBRE_BARRIO: 'Francisco Antonio Zea',
    NOMBRE_COMUNA: 'CASTILLA',
  },
  {
    COMUNA: 5,
    BARRIO: 19,
    NOMBRE_BARRIO: 'El Progreso',
    NOMBRE_COMUNA: 'CASTILLA',
  },
  {
    COMUNA: 5,
    BARRIO: 14,
    NOMBRE_BARRIO: 'Alfonso López',
    NOMBRE_COMUNA: 'CASTILLA',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 6,
    BARRIO: 1,
    NOMBRE_BARRIO: 'Santander',
    NOMBRE_COMUNA: 'DOCE DE OCTUBRE',
  },
  {
    COMUNA: 6,
    BARRIO: 8,
    NOMBRE_BARRIO: 'Picacho',
    NOMBRE_COMUNA: 'DOCE DE OCTUBRE',
  },
  {
    COMUNA: 6,
    BARRIO: 10,
    NOMBRE_BARRIO: 'Mirador del Doce',
    NOMBRE_COMUNA: 'DOCE DE OCTUBRE',
  },
  {
    COMUNA: 6,
    BARRIO: 7,
    NOMBRE_BARRIO: 'Kennedy',
    NOMBRE_COMUNA: 'DOCE DE OCTUBRE',
  },
  {
    COMUNA: 6,
    BARRIO: 4,
    NOMBRE_BARRIO: 'Pedregal',
    NOMBRE_COMUNA: 'DOCE DE OCTUBRE',
  },
  {
    COMUNA: 6,
    BARRIO: 11,
    NOMBRE_BARRIO: 'El Progreso No.2',
    NOMBRE_COMUNA: 'DOCE DE OCTUBRE',
  },
  {
    COMUNA: 6,
    BARRIO: 3,
    NOMBRE_BARRIO: 'Doce de Octubre No.2',
    NOMBRE_COMUNA: 'DOCE DE OCTUBRE',
  },
  {
    COMUNA: 6,
    BARRIO: 5,
    NOMBRE_BARRIO: 'La Esperanza',
    NOMBRE_COMUNA: 'DOCE DE OCTUBRE',
  },
  {
    COMUNA: 6,
    BARRIO: 12,
    NOMBRE_BARRIO: 'El Triunfo',
    NOMBRE_COMUNA: 'DOCE DE OCTUBRE',
  },
  {
    COMUNA: 6,
    BARRIO: 6,
    NOMBRE_BARRIO: 'San Martín de Porres',
    NOMBRE_COMUNA: 'DOCE DE OCTUBRE',
  },
  {
    COMUNA: 6,
    BARRIO: 2,
    NOMBRE_BARRIO: 'Doce de Octubre No.1',
    NOMBRE_COMUNA: 'DOCE DE OCTUBRE',
  },
  {
    COMUNA: 6,
    BARRIO: 9,
    NOMBRE_BARRIO: 'Picachito',
    NOMBRE_COMUNA: 'DOCE DE OCTUBRE',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 7,
    BARRIO: 7,
    NOMBRE_BARRIO: 'Bosques de San Pablo',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 3,
    NOMBRE_BARRIO: 'San Germán',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 17,
    NOMBRE_BARRIO: 'Robledo',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 18,
    NOMBRE_BARRIO: 'Cucaracho',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 20,
    NOMBRE_BARRIO: 'Santa Margarita',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 23,
    NOMBRE_BARRIO: 'Pajarito',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 13,
    NOMBRE_BARRIO: 'Aures No.1',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 12,
    NOMBRE_BARRIO: 'Aures No. 2',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 10,
    NOMBRE_BARRIO: 'López de Mesa',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 15,
    NOMBRE_BARRIO: 'Villa Flora',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 2,
    NOMBRE_BARRIO: 'B. Cerro  El Volador',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 14,
    NOMBRE_BARRIO: 'Bello Horizonte',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 5,
    NOMBRE_BARRIO: 'Facultad de Minas U. Nacional',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 22,
    NOMBRE_BARRIO: 'Olaya Herrera',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 6,
    NOMBRE_BARRIO: 'La Pilarica',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 8,
    NOMBRE_BARRIO: 'Altamira',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 19,
    NOMBRE_BARRIO: 'Fuente Clara',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 25,
    NOMBRE_BARRIO: 'Nueva Villa de la Iguaná',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 9,
    NOMBRE_BARRIO: 'Córdoba',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 24,
    NOMBRE_BARRIO: 'Monteclaro',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 11,
    NOMBRE_BARRIO: 'El Diamante',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 1,
    NOMBRE_BARRIO: 'Universidad Nacional',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 16,
    NOMBRE_BARRIO: 'Palenque',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: 7,
    BARRIO: 4,
    NOMBRE_BARRIO: 'Facultad Veterinaria y Zootecnia U.de.A.',
    NOMBRE_COMUNA: 'ROBLEDO',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 8,
    BARRIO: 17,
    NOMBRE_BARRIO: 'La Sierra',
    NOMBRE_COMUNA: 'VILLA HERMOSA',
  },
  {
    COMUNA: 8,
    BARRIO: 9,
    NOMBRE_BARRIO: 'Sucre',
    NOMBRE_COMUNA: 'VILLA HERMOSA',
  },
  {
    COMUNA: 8,
    BARRIO: 10,
    NOMBRE_BARRIO: 'El Pinal',
    NOMBRE_COMUNA: 'VILLA HERMOSA',
  },
  {
    COMUNA: 8,
    BARRIO: 19,
    NOMBRE_BARRIO: 'Villa Liliam',
    NOMBRE_COMUNA: 'VILLA HERMOSA',
  },
  {
    COMUNA: 8,
    BARRIO: 14,
    NOMBRE_BARRIO: 'San Antonio',
    NOMBRE_COMUNA: 'VILLA HERMOSA',
  },
  {
    COMUNA: 8,
    BARRIO: 7,
    NOMBRE_BARRIO: 'Los Mangos',
    NOMBRE_COMUNA: 'VILLA HERMOSA',
  },
  {
    COMUNA: 8,
    BARRIO: 12,
    NOMBRE_BARRIO: 'La Libertad',
    NOMBRE_COMUNA: 'VILLA HERMOSA',
  },
  {
    COMUNA: 8,
    BARRIO: 6,
    NOMBRE_BARRIO: 'Llanaditas',
    NOMBRE_COMUNA: 'VILLA HERMOSA',
  },
  {
    COMUNA: 8,
    BARRIO: 15,
    NOMBRE_BARRIO: 'Las Estancias',
    NOMBRE_COMUNA: 'VILLA HERMOSA',
  },
  {
    COMUNA: 8,
    BARRIO: 1,
    NOMBRE_BARRIO: 'Villa Hermosa',
    NOMBRE_COMUNA: 'VILLA HERMOSA',
  },
  {
    COMUNA: 8,
    BARRIO: 13,
    NOMBRE_BARRIO: 'Villatina',
    NOMBRE_COMUNA: 'VILLA HERMOSA',
  },
  {
    COMUNA: 8,
    BARRIO: 5,
    NOMBRE_BARRIO: 'Batallón Girardot',
    NOMBRE_COMUNA: 'VILLA HERMOSA',
  },
  {
    COMUNA: 8,
    BARRIO: 16,
    NOMBRE_BARRIO: 'Villa Turbay',
    NOMBRE_COMUNA: 'VILLA HERMOSA',
  },
  {
    COMUNA: 8,
    BARRIO: 8,
    NOMBRE_BARRIO: 'Enciso',
    NOMBRE_COMUNA: 'VILLA HERMOSA',
  },
  {
    COMUNA: 8,
    BARRIO: 2,
    NOMBRE_BARRIO: 'La Mansión',
    NOMBRE_COMUNA: 'VILLA HERMOSA',
  },
  {
    COMUNA: 8,
    BARRIO: 11,
    NOMBRE_BARRIO: 'Trece de Noviembre',
    NOMBRE_COMUNA: 'VILLA HERMOSA',
  },
  {
    COMUNA: 8,
    BARRIO: 3,
    NOMBRE_BARRIO: 'San Miguel',
    NOMBRE_COMUNA: 'VILLA HERMOSA',
  },
  {
    COMUNA: 8,
    BARRIO: 4,
    NOMBRE_BARRIO: 'La Ladera',
    NOMBRE_COMUNA: 'VILLA HERMOSA',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 9,
    BARRIO: 11,
    NOMBRE_BARRIO: 'Gerona',
    NOMBRE_COMUNA: 'BUENOS AIRES',
  },
  {
    COMUNA: 9,
    BARRIO: 2,
    NOMBRE_BARRIO: 'Barrio de Jesús',
    NOMBRE_COMUNA: 'BUENOS AIRES',
  },
  {
    COMUNA: 9,
    BARRIO: 3,
    NOMBRE_BARRIO: 'Bomboná No. 2',
    NOMBRE_COMUNA: 'BUENOS AIRES',
  },
  {
    COMUNA: 9,
    BARRIO: 9,
    NOMBRE_BARRIO: 'Cataluña',
    NOMBRE_COMUNA: 'BUENOS AIRES',
  },
  {
    COMUNA: 9,
    BARRIO: 1,
    NOMBRE_BARRIO: 'Juan Pablo II',
    NOMBRE_COMUNA: 'BUENOS AIRES',
  },
  {
    COMUNA: 9,
    BARRIO: 12,
    NOMBRE_BARRIO: 'El Salvador',
    NOMBRE_COMUNA: 'BUENOS AIRES',
  },
  {
    COMUNA: 9,
    BARRIO: 15,
    NOMBRE_BARRIO: 'Asomadera No. 2',
    NOMBRE_COMUNA: 'BUENOS AIRES',
  },
  {
    COMUNA: 9,
    BARRIO: 8,
    NOMBRE_BARRIO: 'Miraflores',
    NOMBRE_COMUNA: 'BUENOS AIRES',
  },
  {
    COMUNA: 9,
    BARRIO: 6,
    NOMBRE_BARRIO: 'Barrio Caicedo',
    NOMBRE_COMUNA: 'BUENOS AIRES',
  },
  {
    COMUNA: 9,
    BARRIO: 14,
    NOMBRE_BARRIO: 'Asomadera No. 1',
    NOMBRE_COMUNA: 'BUENOS AIRES',
  },
  {
    COMUNA: 9,
    BARRIO: 10,
    NOMBRE_BARRIO: 'La Milagrosa',
    NOMBRE_COMUNA: 'BUENOS AIRES',
  },
  {
    COMUNA: 9,
    BARRIO: 13,
    NOMBRE_BARRIO: 'Loreto',
    NOMBRE_COMUNA: 'BUENOS AIRES',
  },
  {
    COMUNA: 9,
    BARRIO: 7,
    NOMBRE_BARRIO: 'Buenos Aires',
    NOMBRE_COMUNA: 'BUENOS AIRES',
  },
  {
    COMUNA: 9,
    BARRIO: 5,
    NOMBRE_BARRIO: 'Alejandro Echavarría',
    NOMBRE_COMUNA: 'BUENOS AIRES',
  },
  {
    COMUNA: 9,
    BARRIO: 4,
    NOMBRE_BARRIO: 'Los Cerros El Vergel',
    NOMBRE_COMUNA: 'BUENOS AIRES',
  },
  {
    COMUNA: 9,
    BARRIO: 16,
    NOMBRE_BARRIO: 'Asomadera No. 3',
    NOMBRE_COMUNA: 'BUENOS AIRES',
  },
  {
    COMUNA: 9,
    BARRIO: 17,
    NOMBRE_BARRIO: 'Ocho de Marzo',
    NOMBRE_COMUNA: 'BUENOS AIRES',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 10,
    BARRIO: 16,
    NOMBRE_BARRIO: 'Boston',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 14,
    NOMBRE_BARRIO: 'Las Palmas',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 5,
    NOMBRE_BARRIO: 'Estación Villa',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 9,
    NOMBRE_BARRIO: 'La Alpujarra',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 10,
    NOMBRE_BARRIO: 'Centro Administrativo',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 4,
    NOMBRE_BARRIO: 'El Chagualo',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 7,
    NOMBRE_BARRIO: 'Guayaquil',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 19,
    NOMBRE_BARRIO: 'La Candelaria',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 20,
    NOMBRE_BARRIO: 'San Diego',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 6,
    NOMBRE_BARRIO: 'San Benito',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 13,
    NOMBRE_BARRIO: 'Barrio Colón',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 1,
    NOMBRE_BARRIO: 'Prado',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 3,
    NOMBRE_BARRIO: 'Jesús Nazareno',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 2,
    NOMBRE_BARRIO: 'Hospital San Vicente de Paúl',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 8,
    NOMBRE_BARRIO: 'Corazón de Jesús',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 17,
    NOMBRE_BARRIO: 'Los Ángeles',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 11,
    NOMBRE_BARRIO: 'Calle Nueva',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 12,
    NOMBRE_BARRIO: 'Perpetuo Socorro',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 18,
    NOMBRE_BARRIO: 'Villa Nueva',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: 10,
    BARRIO: 15,
    NOMBRE_BARRIO: 'Bomboná No. 1',
    NOMBRE_COMUNA: 'LA CANDELARIA',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 11,
    BARRIO: 5,
    NOMBRE_BARRIO: 'Los Conquistadores',
    NOMBRE_COMUNA: 'LAURELES',
  },
  {
    COMUNA: 11,
    BARRIO: 7,
    NOMBRE_BARRIO: 'Bolivariana',
    NOMBRE_COMUNA: 'LAURELES',
  },
  {
    COMUNA: 11,
    BARRIO: 4,
    NOMBRE_BARRIO: 'San Joaquín',
    NOMBRE_COMUNA: 'LAURELES',
  },
  {
    COMUNA: 11,
    BARRIO: 2,
    NOMBRE_BARRIO: 'Suramericana',
    NOMBRE_COMUNA: 'LAURELES',
  },
  {
    COMUNA: 11,
    BARRIO: 16,
    NOMBRE_BARRIO: 'U.D. Atanasio Girardot',
    NOMBRE_COMUNA: 'LAURELES',
  },
  {
    COMUNA: 11,
    BARRIO: 9,
    NOMBRE_BARRIO: 'Las Acacias',
    NOMBRE_COMUNA: 'LAURELES',
  },
  {
    COMUNA: 11,
    BARRIO: 1,
    NOMBRE_BARRIO: 'Carlos E. Restrepo',
    NOMBRE_COMUNA: 'LAURELES',
  },
  {
    COMUNA: 11,
    BARRIO: 17,
    NOMBRE_BARRIO: 'Florida Nueva',
    NOMBRE_COMUNA: 'LAURELES',
  },
  {
    COMUNA: 11,
    BARRIO: 3,
    NOMBRE_BARRIO: 'Naranjal',
    NOMBRE_COMUNA: 'LAURELES',
  },
  {
    COMUNA: 11,
    BARRIO: 8,
    NOMBRE_BARRIO: 'Laureles',
    NOMBRE_COMUNA: 'LAURELES',
  },
  {
    COMUNA: 11,
    BARRIO: 15,
    NOMBRE_BARRIO: 'Cuarta Brigada',
    NOMBRE_COMUNA: 'LAURELES',
  },
  {
    COMUNA: 11,
    BARRIO: 11,
    NOMBRE_BARRIO: 'Lorena',
    NOMBRE_COMUNA: 'LAURELES',
  },
  {
    COMUNA: 11,
    BARRIO: 12,
    NOMBRE_BARRIO: 'El Velódromo',
    NOMBRE_COMUNA: 'LAURELES',
  },
  {
    COMUNA: 11,
    BARRIO: 10,
    NOMBRE_BARRIO: 'La Castellana',
    NOMBRE_COMUNA: 'LAURELES',
  },
  {
    COMUNA: 11,
    BARRIO: 13,
    NOMBRE_BARRIO: 'El Estadio',
    NOMBRE_COMUNA: 'LAURELES',
  },
  {
    COMUNA: 11,
    BARRIO: 14,
    NOMBRE_BARRIO: 'Los Colores',
    NOMBRE_COMUNA: 'LAURELES',
  },
  {
    COMUNA: 11,
    BARRIO: 6,
    NOMBRE_BARRIO: 'U.P.B.',
    NOMBRE_COMUNA: 'LAURELES',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 12,
    BARRIO: 3,
    NOMBRE_BARRIO: 'Los Pinos',
    NOMBRE_COMUNA: 'LA AMERICA',
  },
  {
    COMUNA: 12,
    BARRIO: 10,
    NOMBRE_BARRIO: 'Barrio Cristóbal',
    NOMBRE_COMUNA: 'LA AMERICA',
  },
  {
    COMUNA: 12,
    BARRIO: 11,
    NOMBRE_BARRIO: 'Simón Bolívar',
    NOMBRE_COMUNA: 'LA AMERICA',
  },
  {
    COMUNA: 12,
    BARRIO: 4,
    NOMBRE_BARRIO: 'La América',
    NOMBRE_COMUNA: 'LA AMERICA',
  },
  {
    COMUNA: 12,
    BARRIO: 13,
    NOMBRE_BARRIO: 'Calasanz Parte Alta',
    NOMBRE_COMUNA: 'LA AMERICA',
  },
  {
    COMUNA: 12,
    BARRIO: 2,
    NOMBRE_BARRIO: 'Calasanz',
    NOMBRE_COMUNA: 'LA AMERICA',
  },
  {
    COMUNA: 12,
    BARRIO: 9,
    NOMBRE_BARRIO: 'Santa Mónica',
    NOMBRE_COMUNA: 'LA AMERICA',
  },
  {
    COMUNA: 12,
    BARRIO: 7,
    NOMBRE_BARRIO: 'El Danubio',
    NOMBRE_COMUNA: 'LA AMERICA',
  },
  {
    COMUNA: 12,
    BARRIO: 1,
    NOMBRE_BARRIO: 'Ferrini',
    NOMBRE_COMUNA: 'LA AMERICA',
  },
  {
    COMUNA: 12,
    BARRIO: 6,
    NOMBRE_BARRIO: 'Santa Lucía',
    NOMBRE_COMUNA: 'LA AMERICA',
  },
  {
    COMUNA: 12,
    BARRIO: 8,
    NOMBRE_BARRIO: 'Campo Alegre',
    NOMBRE_COMUNA: 'LA AMERICA',
  },
  {
    COMUNA: 12,
    BARRIO: 5,
    NOMBRE_BARRIO: 'La Floresta',
    NOMBRE_COMUNA: 'LA AMERICA',
  },
  {
    COMUNA: 12,
    BARRIO: 12,
    NOMBRE_BARRIO: 'Santa Teresita',
    NOMBRE_COMUNA: 'LA AMERICA',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 13,
    BARRIO: 13,
    NOMBRE_BARRIO: 'El Corazón',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: 13,
    BARRIO: 9,
    NOMBRE_BARRIO: 'San Javier No.1',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: 13,
    BARRIO: 17,
    NOMBRE_BARRIO: 'Eduardo Santos',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: 13,
    BARRIO: 19,
    NOMBRE_BARRIO: 'El Socorro',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: 13,
    BARRIO: 12,
    NOMBRE_BARRIO: 'Betania',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: 13,
    BARRIO: 8,
    NOMBRE_BARRIO: 'San Javier No.2',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: 13,
    BARRIO: 11,
    NOMBRE_BARRIO: 'Belencito',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: 13,
    BARRIO: 14,
    NOMBRE_BARRIO: 'Las Independencias',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: 13,
    BARRIO: 16,
    NOMBRE_BARRIO: 'El Salado',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: 13,
    BARRIO: 15,
    NOMBRE_BARRIO: 'Nuevos Conquistadores',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: 13,
    BARRIO: 3,
    NOMBRE_BARRIO: 'Santa Rosa de Lima',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: 13,
    BARRIO: 7,
    NOMBRE_BARRIO: 'Juan XXIII La Quiebra',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: 13,
    BARRIO: 18,
    NOMBRE_BARRIO: 'Antonio Nariño',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: 13,
    BARRIO: 4,
    NOMBRE_BARRIO: 'Los Alcázares',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: 13,
    BARRIO: 6,
    NOMBRE_BARRIO: 'La Pradera',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: 13,
    BARRIO: 2,
    NOMBRE_BARRIO: 'Blanquizal',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: 13,
    BARRIO: 10,
    NOMBRE_BARRIO: 'Veinte de Julio',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: 13,
    BARRIO: 1,
    NOMBRE_BARRIO: 'El Pesebre',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: 13,
    BARRIO: 5,
    NOMBRE_BARRIO: 'Metropolitano',
    NOMBRE_COMUNA: 'SAN JAVIER',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 14,
    BARRIO: 3,
    NOMBRE_BARRIO: 'Villa Carlota',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 23,
    NOMBRE_BARRIO: 'Santa María de los Ángeles',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 7,
    NOMBRE_BARRIO: 'Las Lomas No.2',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 12,
    NOMBRE_BARRIO: 'San Lucas',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 10,
    NOMBRE_BARRIO: 'Los Naranjos',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 13,
    NOMBRE_BARRIO: 'El Diamante No. 2',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 17,
    NOMBRE_BARRIO: 'La Florida',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 18,
    NOMBRE_BARRIO: 'El Poblado',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 16,
    NOMBRE_BARRIO: 'Alejandría',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 22,
    NOMBRE_BARRIO: 'La Aguacatala',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 5,
    NOMBRE_BARRIO: 'Lalinde',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 1,
    NOMBRE_BARRIO: 'Barrio Colombia',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 8,
    NOMBRE_BARRIO: 'Altos del Poblado',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 21,
    NOMBRE_BARRIO: 'Patio Bonito',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 4,
    NOMBRE_BARRIO: 'Castropol',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 9,
    NOMBRE_BARRIO: 'El Tesoro',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 14,
    NOMBRE_BARRIO: 'El Castillo',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 6,
    NOMBRE_BARRIO: 'Las Lomas No.1',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 20,
    NOMBRE_BARRIO: 'Astorga',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 11,
    NOMBRE_BARRIO: 'Los Balsos No.1',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 15,
    NOMBRE_BARRIO: 'Los Balsos No.2',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: 14,
    BARRIO: 19,
    NOMBRE_BARRIO: 'Manila',
    NOMBRE_COMUNA: 'EL POBLADO',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 15,
    BARRIO: 1,
    NOMBRE_BARRIO: 'El Rodeo',
    NOMBRE_COMUNA: 'GUAYABAL',
  },
  {
    COMUNA: 15,
    BARRIO: 3,
    NOMBRE_BARRIO: 'Trinidad',
    NOMBRE_COMUNA: 'GUAYABAL',
  },
  {
    COMUNA: 15,
    BARRIO: 6,
    NOMBRE_BARRIO: 'Parque Juan Pablo II',
    NOMBRE_COMUNA: 'GUAYABAL',
  },
  {
    COMUNA: 15,
    BARRIO: 4,
    NOMBRE_BARRIO: 'Santa Fé',
    NOMBRE_COMUNA: 'GUAYABAL',
  },
  {
    COMUNA: 15,
    BARRIO: 10,
    NOMBRE_BARRIO: 'Guayabal',
    NOMBRE_COMUNA: 'GUAYABAL',
  },
  {
    COMUNA: 15,
    BARRIO: 9,
    NOMBRE_BARRIO: 'Cristo Rey',
    NOMBRE_COMUNA: 'GUAYABAL',
  },
  {
    COMUNA: 15,
    BARRIO: 2,
    NOMBRE_BARRIO: 'Tenche',
    NOMBRE_COMUNA: 'GUAYABAL',
  },
  {
    COMUNA: 15,
    BARRIO: 7,
    NOMBRE_BARRIO: 'Campo Amor',
    NOMBRE_COMUNA: 'GUAYABAL',
  },
  {
    COMUNA: 15,
    BARRIO: 11,
    NOMBRE_BARRIO: 'La Colina',
    NOMBRE_COMUNA: 'GUAYABAL',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 16,
    BARRIO: 18,
    NOMBRE_BARRIO: 'Nueva Villa de Aburrá',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 9,
    NOMBRE_BARRIO: 'La Hondonada',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 7,
    NOMBRE_BARRIO: 'Diego Echavarría',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 5,
    NOMBRE_BARRIO: 'San Bernardo',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 11,
    NOMBRE_BARRIO: 'Loma de los Bernal',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 13,
    NOMBRE_BARRIO: 'Altavista',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 4,
    NOMBRE_BARRIO: 'Granada',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 3,
    NOMBRE_BARRIO: 'Belén',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 14,
    NOMBRE_BARRIO: 'La Palma',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 16,
    NOMBRE_BARRIO: 'Las Violetas',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 15,
    NOMBRE_BARRIO: 'Los Alpes',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 10,
    NOMBRE_BARRIO: 'El Rincón',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 12,
    NOMBRE_BARRIO: 'La Gloria',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 17,
    NOMBRE_BARRIO: 'Las Mercedes',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 6,
    NOMBRE_BARRIO: 'Las Playas',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 1,
    NOMBRE_BARRIO: 'Fátima',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 8,
    NOMBRE_BARRIO: 'La mota',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 19,
    NOMBRE_BARRIO: 'Miravalle',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 2,
    NOMBRE_BARRIO: 'Rosales',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 20,
    NOMBRE_BARRIO: 'El Nogal-Los Almendros',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: 16,
    BARRIO: 21,
    NOMBRE_BARRIO: 'Cerro Nutibara',
    NOMBRE_COMUNA: 'BELEN',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 50,
    BARRIO: 6,
    NOMBRE_BARRIO: 'Potrera Miserenga',
    NOMBRE_COMUNA: 'PALMITAS',
  },
  {
    COMUNA: 50,
    BARRIO: 1,
    NOMBRE_BARRIO: 'La Suiza',
    NOMBRE_COMUNA: 'PALMITAS',
  },
  {
    COMUNA: 50,
    BARRIO: 2,
    NOMBRE_BARRIO: 'La Frisola',
    NOMBRE_COMUNA: 'PALMITAS',
  },
  {
    COMUNA: 50,
    BARRIO: 3,
    NOMBRE_BARRIO: 'Volcana Guayabal',
    NOMBRE_COMUNA: 'PALMITAS',
  },
  {
    COMUNA: 50,
    BARRIO: 4,
    NOMBRE_BARRIO: 'Palmitas Sector Central',
    NOMBRE_COMUNA: 'PALMITAS',
  },
  {
    COMUNA: 50,
    BARRIO: 7,
    NOMBRE_BARRIO: 'La Urquita',
    NOMBRE_COMUNA: 'PALMITAS',
  },
  {
    COMUNA: 50,
    BARRIO: 87,
    NOMBRE_BARRIO: 'Suburbano Potrera Miserenga',
    NOMBRE_COMUNA: 'PALMITAS',
  },
  {
    COMUNA: 50,
    BARRIO: 88,
    NOMBRE_BARRIO: 'Suburbano La Aldea',
    NOMBRE_COMUNA: 'PALMITAS',
  },
  {
    COMUNA: 50,
    BARRIO: 5,
    NOMBRE_BARRIO: 'La Aldea',
    NOMBRE_COMUNA: 'PALMITAS',
  },
  {
    COMUNA: 50,
    BARRIO: 89,
    NOMBRE_BARRIO: 'Suburbano Palmitas',
    NOMBRE_COMUNA: 'PALMITAS',
  },
  {
    COMUNA: 50,
    BARRIO: 86,
    NOMBRE_BARRIO: 'Suburbano Urquita',
    NOMBRE_COMUNA: 'PALMITAS',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 60,
    BARRIO: 16,
    NOMBRE_BARRIO: 'Boqueron',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 0,
    NOMBRE_BARRIO: 'Cabecera Urbana San Cristobal',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 88,
    NOMBRE_BARRIO: 'Suburbano El Llano',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 97,
    NOMBRE_BARRIO: 'Area de Expansion Altos de Calasanz',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 85,
    NOMBRE_BARRIO: 'Suburbano La Palma-El Patio',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 1,
    NOMBRE_BARRIO: 'La Loma',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 11,
    NOMBRE_BARRIO: 'Pajarito',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 89,
    NOMBRE_BARRIO: 'Suburbano Pedregal alto',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 8,
    NOMBRE_BARRIO: 'Travesías',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 9,
    NOMBRE_BARRIO: 'Pedregal Alto',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 7,
    NOMBRE_BARRIO: 'El Llano',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 6,
    NOMBRE_BARRIO: 'La Cuchilla',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 2,
    NOMBRE_BARRIO: 'La Palma-El Patio',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 98,
    NOMBRE_BARRIO: 'Área de Expansión Pajarito',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 86,
    NOMBRE_BARRIO: 'Suburbano La Cuchilla',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 13,
    NOMBRE_BARRIO: 'El Carmelo',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 14,
    NOMBRE_BARRIO: 'Yolombo',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 15,
    NOMBRE_BARRIO: 'San José de la Montaña',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 12,
    NOMBRE_BARRIO: 'El Picacho',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 84,
    NOMBRE_BARRIO: 'Suburbano La Loma',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 10,
    NOMBRE_BARRIO: 'Pedregal Bajo',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 17,
    NOMBRE_BARRIO: 'La Loma Oriental',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 5,
    NOMBRE_BARRIO: 'Naranjal',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 4,
    NOMBRE_BARRIO: 'El Uvito',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 3,
    NOMBRE_BARRIO: 'Las Playas',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: 60,
    BARRIO: 87,
    NOMBRE_BARRIO: 'Suburbano Travesias',
    NOMBRE_COMUNA: 'SAN CRISTOBAL',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 70,
    BARRIO: 96,
    NOMBRE_BARRIO: 'Area De Expansion Altavista',
    NOMBRE_COMUNA: 'ALTAVISTA',
  },
  {
    COMUNA: 70,
    BARRIO: 2,
    NOMBRE_BARRIO: 'Aguas Frias',
    NOMBRE_COMUNA: 'ALTAVISTA',
  },
  {
    COMUNA: 70,
    BARRIO: 97,
    NOMBRE_BARRIO: 'Area De Expansion Belen Rincon',
    NOMBRE_COMUNA: 'ALTAVISTA',
  },
  {
    COMUNA: 70,
    BARRIO: 98,
    NOMBRE_BARRIO: 'Area De Expansion El Noral',
    NOMBRE_COMUNA: 'ALTAVISTA',
  },
  {
    COMUNA: 70,
    BARRIO: 85,
    NOMBRE_BARRIO: 'San Pablo',
    NOMBRE_COMUNA: 'ALTAVISTA',
  },
  {
    COMUNA: 70,
    BARRIO: 88,
    NOMBRE_BARRIO: 'El Corazon El Morro',
    NOMBRE_COMUNA: 'ALTAVISTA',
  },
  {
    COMUNA: 70,
    BARRIO: 1,
    NOMBRE_BARRIO: 'Altavista Sector Central',
    NOMBRE_COMUNA: 'ALTAVISTA',
  },
  {
    COMUNA: 70,
    BARRIO: 89,
    NOMBRE_BARRIO: 'San Jose Del Manzanillo',
    NOMBRE_COMUNA: 'ALTAVISTA',
  },
  {
    COMUNA: 70,
    BARRIO: 86,
    NOMBRE_BARRIO: 'Suburbano Aguas Frias',
    NOMBRE_COMUNA: 'ALTAVISTA',
  },
  {
    COMUNA: 70,
    BARRIO: 84,
    NOMBRE_BARRIO: 'Buga Patio Bonito',
    NOMBRE_COMUNA: 'ALTAVISTA',
  },
  {
    COMUNA: 70,
    BARRIO: 87,
    NOMBRE_BARRIO: 'Suburbano Altavista',
    NOMBRE_COMUNA: 'ALTAVISTA',
  },
  {
    COMUNA: 70,
    BARRIO: 83,
    NOMBRE_BARRIO: 'La Esperanza',
    NOMBRE_COMUNA: 'ALTAVISTA',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 80,
    BARRIO: 6,
    NOMBRE_BARRIO: 'El Salado',
    NOMBRE_COMUNA: 'SAN ANTONIO DE PRADO',
  },
  {
    COMUNA: 80,
    BARRIO: 7,
    NOMBRE_BARRIO: 'El Astillero',
    NOMBRE_COMUNA: 'SAN ANTONIO DE PRADO',
  },
  {
    COMUNA: 80,
    BARRIO: 1,
    NOMBRE_BARRIO: 'El Vergel',
    NOMBRE_COMUNA: 'SAN ANTONIO DE PRADO',
  },
  {
    COMUNA: 80,
    BARRIO: 4,
    NOMBRE_BARRIO: 'La Oculta',
    NOMBRE_COMUNA: 'SAN ANTONIO DE PRADO',
  },
  {
    COMUNA: 80,
    BARRIO: 0,
    NOMBRE_BARRIO: 'Cabecera San Antonio de Prado',
    NOMBRE_COMUNA: 'SAN ANTONIO DE PRADO',
  },
  {
    COMUNA: 80,
    BARRIO: 3,
    NOMBRE_BARRIO: 'Potrerito',
    NOMBRE_COMUNA: 'SAN ANTONIO DE PRADO',
  },
  {
    COMUNA: 80,
    BARRIO: 8,
    NOMBRE_BARRIO: 'Yarumalito',
    NOMBRE_COMUNA: 'SAN ANTONIO DE PRADO',
  },
  {
    COMUNA: 80,
    BARRIO: 89,
    NOMBRE_BARRIO: 'Suburbano Potrerito',
    NOMBRE_COMUNA: 'SAN ANTONIO DE PRADO',
  },
  {
    COMUNA: 80,
    BARRIO: 5,
    NOMBRE_BARRIO: 'La Verde',
    NOMBRE_COMUNA: 'SAN ANTONIO DE PRADO',
  },
  {
    COMUNA: 80,
    BARRIO: 2,
    NOMBRE_BARRIO: 'La Florida',
    NOMBRE_COMUNA: 'SAN ANTONIO DE PRADO',
  },
  {
    COMUNA: 80,
    BARRIO: 98,
    NOMBRE_BARRIO: 'Área de Expansión San Antonio de Prado',
    NOMBRE_COMUNA: 'SAN ANTONIO DE PRADO',
  },
  {
    COMUNA: '',
    BARRIO: '',
    NOMBRE_BARRIO: '',
    NOMBRE_COMUNA: '',
  },
  {
    COMUNA: 90,
    BARRIO: 12,
    NOMBRE_BARRIO: 'Piedra Gorda',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 6,
    NOMBRE_BARRIO: 'Santa Elena Sector Central',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 89,
    NOMBRE_BARRIO: 'Suburbano Matasano 1',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 79,
    NOMBRE_BARRIO: 'Suburbano Piedra Gorda',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 11,
    NOMBRE_BARRIO: 'Piedras Blancas Represa',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 13,
    NOMBRE_BARRIO: 'Barro Blanco',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 81,
    NOMBRE_BARRIO: 'Suburbano El Placer',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 7,
    NOMBRE_BARRIO: 'El Placer',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 84,
    NOMBRE_BARRIO: 'Suburbano Santa Elena Central',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 78,
    NOMBRE_BARRIO: 'Suburbano El Cerro',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 3,
    NOMBRE_BARRIO: 'El Plan',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 85,
    NOMBRE_BARRIO: 'Suburbano El Llano',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 82,
    NOMBRE_BARRIO: 'Suburbano Chacaltaya',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 88,
    NOMBRE_BARRIO: 'Suburbano Matasano 2',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 8,
    NOMBRE_BARRIO: 'Piedras Blancas',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 86,
    NOMBRE_BARRIO: 'SUBURB El Plan',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 77,
    NOMBRE_BARRIO: 'Suburbano el Tesoro',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 87,
    NOMBRE_BARRIO: 'Suburbano Matasano 3',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 2,
    NOMBRE_BARRIO: 'El Llano SE',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 83,
    NOMBRE_BARRIO: 'Suburbano Mirador del Poblado',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 1,
    NOMBRE_BARRIO: 'El Cerro',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 80,
    NOMBRE_BARRIO: 'Suburbano Barro Blanco',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
  {
    COMUNA: 90,
    BARRIO: 5,
    NOMBRE_BARRIO: 'Media Luna',
    NOMBRE_COMUNA: 'SANTA ELENA',
  },
]
