module.exports = {
  mode: 'jit',
  purge: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        color_primary_1: '#FE7C1A',
        color_primary_1_ligth: '#EC7B29',
        color_primary_2: '#016CFA',
        color_primary_2_transparent: '#E3EFFD',
        color_primary_2_ligth: '#01B0F3',
        color_primary_2_dark: '#0067D0',
        color_gray_1: '#FFFFFF',
        color_gray_2: '#F4F4F4',
        color_gray_3: '#707070',
        color_gray_4: '#C1C1C1',
        color_gray_5: '#BCBCBC',
        color_gray_6: '#BEBEBE',
        color_gray_7: '#E0E0E0',
        color_gray_8: '#EDEDED',
        color_red: '#ff4949',
        color_orange: '#ff8828',
        color_green: '#18d24c',
        color_black_1: '#575756',
      },
      fontFamily: {
        body: ['Montserrat'],
        section: ['Work Sans'],
      },
      fontSize: {
        xs: '.75rem',
        sm: '.875rem',
        tiny: '.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.375rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '4rem',
        '7xl': '5rem',
      },
      height: {
        sm: '27rem',
        md: '33rem',
        md_1: '35rem',
        md_2: '40rem',
        lg: '45rem',
        xl: '50rem',
      },
      width: {
        sm: '30rem',
        md: '33rem',
        45: '45%',
      },
      gridTemplateColumns: {
        16: 'repeat(5, 190px);',
      },
      zIndex: {
        0: 0,
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: 10,
        20: 20,
        30: 30,
        40: 40,
        50: 50,
        60: 60,
        70: 70,
        80: 80,
        90: 90,
        100: 100,
        auto: 'auto',
      },
    },
  },
  variants: {
    display: ['responsive', 'group-hover', 'group-focus'],
  },
  plugins: [],
}
