export const dataPopulationVariables = [
  {
    id: 23,
    name: 'gender',
    fieldName: 'Sexo',
    type: 'radio',
    className: '',
    options: [
      {
        id: 23.1,
        referenceName: 'gender',
        name: 'male',
        fieldName: 'Masculino',
        type: 'radio',
        className: '',
      },
      {
        id: 23.2,
        referenceName: 'gender',
        name: 'female',
        fieldName: 'Femenino',
        type: 'radio',
        className: '',
      },
    ],
  },
  {
    id: 24,
    name: 'sexualOrientation',
    fieldName: 'Orientación sexual',
    type: 'radio',
    className: '',
    options: [
      {
        id: 24.1,
        referenceName: 'sexualOrientation',
        name: 'lgtbi',
        fieldName: 'LGTBI',
        type: 'radio',
        className: '',
      },
      {
        id: 24.2,
        referenceName: 'sexualOrientation',
        name: 'no',
        fieldName: 'No',
        type: 'radio',
        className: '',
      },
    ],
  },
  {
    id: 25,
    name: 'ethnicity',
    fieldName: 'Etnia',
    type: 'radio',
    className: '',
    options: [
      {
        id: 25.1,
        referenceName: 'ethnicity',
        name: 'afroColombiano',
        fieldName: 'AfroColombiano',
        type: 'radio',
        className: '',
      },
      {
        id: 25.2,
        referenceName: 'ethnicity',
        name: 'indigena',
        fieldName: 'Indígena',
        type: 'radio',
        className: '',
      },
      {
        id: 25.3,
        referenceName: 'ethnicity',
        name: 'negro',
        fieldName: 'Negro',
        type: 'radio',
        className: '',
      },
      {
        id: 25.4,
        referenceName: 'ethnicity',
        name: 'palenqueros',
        fieldName: 'Palenqueros',
        type: 'radio',
        className: '',
      },
      {
        id: 25.5,
        referenceName: 'ethnicity',
        name: 'raizales',
        fieldName: 'Raizales',
        type: 'radio',
        className: '',
      },
      {
        id: 25.6,
        referenceName: 'ethnicity',
        name: 'losRow',
        fieldName: 'Los Row',
        type: 'radio',
        className: '',
      },
      {
        id: 25.7,
        referenceName: 'ethnicity',
        name: 'gitana',
        fieldName: 'Gitana',
        type: 'radio',
        className: '',
      },
      {
        id: 25.8,
        referenceName: 'ethnicity',
        name: 'otro',
        fieldName: 'Otro',
        type: 'radio',
        className: '',
      },
    ],
  },

  {
    id: 26,
    name: 'disability',
    fieldName: 'Discapacidad',
    type: 'radio',
    className: '',
    options: [
      {
        id: 26.1,
        referenceName: 'disability',
        name: 'yes',
        fieldName: 'SI',
        type: 'radio',
        className: '',
      },
      {
        id: 26.2,
        referenceName: 'disability',
        name: 'physic',
        fieldName: 'fisica',
        type: 'radio',
        className: '',
      },
      {
        id: 26.3,
        referenceName: 'disability',
        name: 'visual',
        fieldName: 'Visual',
        type: 'radio',
        className: '',
      },
      {
        id: 26.4,
        referenceName: 'disability',
        name: 'sordoceguera',
        fieldName: 'SordoCeguera',
        type: 'radio',
        className: '',
      },
      {
        id: 26.5,
        referenceName: 'disability',
        name: 'sordo',
        fieldName: 'Sordo',
        type: 'radio',
        className: '',
      },
      {
        id: 26.6,
        referenceName: 'disability',
        name: 'intelectal',
        fieldName: 'intelectal',
        type: 'radio',
        className: '',
      },
      {
        id: 26.7,
        referenceName: 'disability',
        name: 'Psicosocial',
        fieldName: 'Psicosocial (Mental)',
        type: 'radio',
        className: '',
      },
      {
        id: 26.8,
        referenceName: 'disability',
        name: 'multiple',
        fieldName: 'Multiple',
        type: 'radio',
        className: '',
      },
      {
        id: 26.9,
        referenceName: 'disability',
        name: 'NO',
        fieldName: 'NO',
        type: 'radio',
        className: '',
      },
    ],
  },
  {
    id: 28,
    name: 'peasantPopulation',
    fieldName: 'Población campesina',
    type: 'radio',
    className: '',
    options: [
      {
        id: 28.1,
        referenceName: 'peasantPopulation',
        name: 'yes',
        fieldName: 'SI',
        type: 'radio',
        className: '',
      },
      {
        id: 28.2,
        referenceName: 'peasantPopulation',
        name: 'NO',
        fieldName: 'NO',
        type: 'radio',
        className: '',
      },
    ],
  },
  {
    id: 29,
    name: 'maritalStatus',
    fieldName: 'Estado Civíl',
    type: 'radio',
    className: '',
    options: [
      {
        id: 29.1,
        referenceName: 'maritalStatus',
        name: 'single',
        fieldName: 'Soltero',
        type: 'radio',
        className: '',
      },
      {
        id: 29.2,
        referenceName: 'maritalStatus',
        name: 'married',
        fieldName: 'Casado',
        type: 'radio',
        className: '',
      },
      {
        id: 29.3,
        referenceName: 'maritalStatus',
        name: 'widowed',
        fieldName: 'Viudo',
        type: 'radio',
        className: '',
      },
      {
        id: 29.4,
        referenceName: 'maritalStatus',
        name: 'commonLawMarriage',
        fieldName: 'Unión libre',
        type: 'radio',
        className: '',
      },
      {
        id: 29.5,
        referenceName: 'maritalStatus',
        name: 'divorced',
        fieldName: 'Divorciado',
        type: 'radio',
        className: '',
      },
    ],
  },
  {
    id: '1',
    name: 'cabezaDeHogar',
    fieldName: 'Cabeza de Hogar',
    type: 'radio',
    className: '',
    options: [
      {
        id: '28.1',
        referenceName: 'cabezaDeHogar',
        name: 'yes',
        fieldName: 'SI',
        type: 'radio',
        className: '',
      },
      {
        id: '28.o2',
        referenceName: 'cabezaDeHogar',
        name: 'NO',
        fieldName: 'NO',
        type: 'radio',
        className: '',
      },
    ],
  },
  {
    id: 30,
    name: 'educationLevel',
    fieldName: 'Nivel de escolaridad',
    type: 'radio',
    className: '',
    options: [
      {
        id: 30.1,
        referenceName: 'educationLevel',
        name: 'noone',
        fieldName: 'Ninguno',
        type: 'radio',
        className: '',
      },
      {
        id: 30.2,
        referenceName: 'educationLevel',
        name: 'elementarySchool',
        fieldName: 'Primaria',
        type: 'radio',
        className: '',
      },
      {
        id: 30.3,
        referenceName: 'educationLevel',
        name: 'HighSchool',
        fieldName: 'Bachiller',
        type: 'radio',
        className: '',
      },
      {
        id: 30.4,
        referenceName: 'educationLevel',
        name: 'technical',
        fieldName: 'Técnico',
        type: 'radio',
        className: '',
      },
      {
        id: 30.5,
        referenceName: 'educationLevel',
        name: 'technologist',
        fieldName: 'Tecnólogo',
        type: 'radio',
        className: '',
      },
      {
        id: 30.6,
        referenceName: 'educationLevel',
        name: 'professional',
        fieldName: 'Profesional',
        type: 'radio',
        className: '',
      },
      {
        id: 30.7,
        referenceName: 'educationLevel',
        name: 'specialist',
        fieldName: 'Especialista',
        type: 'radio',
        className: '',
      },
      {
        id: 30.7,
        referenceName: 'educationLevel',
        name: 'magister',
        fieldName: 'Magister',
        type: 'radio',
        className: '',
      },
      {
        id: 30.7,
        referenceName: 'educationLevel',
        name: 'doctor',
        fieldName: 'Doctorado',
        type: 'radio',
        className: '',
      },
    ],
  },
]
