export const DataBasicInformation = [
  {
    id: 1,
    name: 'personalId',
    fieldName: 'Tipo de identificacion',
    type: 'select',
    className: '',
    options: [
      // {
      //   id: 1.1,
      //   name: '',
      //   fieldName: '--Selecciona un campo--',
      //   className: '',
      // },
      {
        id: 1.2,
        name: 'c.c',
        fieldName: 'C.C',
        className: '',
      },
      {
        id: 1.3,
        name: 'c.e',
        fieldName: 'C.E',
        className: '',
      },
    ],
  },
  {
    id: 2,
    name: 'numberId',
    fieldName: 'No. De identificación',
    type: 'number',
    className: '',
  },
  {
    id: 3,
    name: 'birthDate',
    fieldName: 'Fecha de nacimiento',
    type: 'date',
    className: '',
  },
  {
    id: 4,
    name: 'firstName',
    fieldName: 'Primer Nombre',
    type: 'text',
    className: '',
  },
  {
    id: 5,
    name: 'SecondName',
    fieldName: 'Segundo Nombre',
    type: 'text',
    className: '',
  },
  {
    id: 6,
    name: 'firstSurname',
    fieldName: 'Primer Apellido',
    type: 'text',
    className: '',
  },
  {
    id: 7,
    name: 'secondSurname',
    fieldName: 'Segundo Apellido',
    type: 'text',
    className: '',
  },
  {
    id: 8,
    name: 'IncomeByMonth',
    fieldName: 'Ingresos Mensuales',
    type: 'number',
    className: '',
  },
  {
    id: 9,
    name: 'ExpensesByMonth',
    fieldName: 'Egresos Mensuales',
    type: 'number',
    className: '',
  },
]
